classDiagram

    Customer <-- Account
    Transaction --> BankStatement
    Account <-- Transaction
    Account <|-- SavingsAccount
    Account <|-- CurrentAccount
    class Customer {
        -List<Account> accounts
        +Account createAccount(int accountNr)
    }

    class Account{
        -string type
        -int accountNr
        -float balance
        +withdraw(int accountNr, float amount)
        +deposit(int accountNr,float amount)
    }
    class CurrentAccount{
        -string type
        -int accountNr
        -float balance
        +withdraw(int accountNr, float amount)
        +deposit(int accountNr,float amount)
    }
    class SavingsAccount{
        -string type
        -int accountNr
        -float balance
        +withdraw(int accountNr, float amount)
        +deposit(int accountNr,float amount)
    }
    class Transaction{
        -float amount
        -string type
        -DateTime timeStamp
        +Transaction createTransaction(float amount, string type, DateTime timeStamp)
    }
    class BankStatement{
        +List<Transaction> transactions
        +printStatement(int accountNr)
    }