classDiagram

    Customer <-- Account
    Transaction --> BankStatement
    Account <|-- Transaction
    
    class Customer {
        +createAccount(int accountNr)
    }

    class Account{
        -string type
        -int accountNr
        -float balance
        +float amount
        +withdraw(int accountNr, float amount)
        +deposit(int accountNr,float amount)
    }
    class Transaction{
        -float amount
        -string type
        -DateTime timeStamp
        +string createTransaction(float amount, string type, DateTime timeStamp)
    }
    class BankStatement{
        +List<Transaction> transactions
        +printStatement(int accountNr)
    }