| Classes        | Methods            | Scenarios              | Output                    |
|----------------|--------------------|------------------------|---------------------------|
|Transaction	 |                    |                        |                           |
|BankAccount     | GenerateStatements | Record of transactions | X deposited and withdrawn |
|                | Deposit            | Depositing X amount    | X Added to your account   |
|                | Withdraw           | Withdrawing X amount   | X withdrawen from account |
|				 |                    |                        |                           |