| Classes        | Methods            | Scenarios              | Output                    |
|----------------|--------------------|------------------------|---------------------------|
| CurrentAccount |                    |                        |                           |
| SavingsAccount |                    |                        |                           |
|                | GenerateStatements | Record of transactions | X deposited and withdrawn |
|                | Deposit            | Depositing X amount    | X Added to your account   |
|                | Withdraw           | Withdrawing X amount   | X withdrawen from account |