@startuml
!include .\\.\Boolean.CSharp.Main\Program.puml
!include .\\.\Boolean.CSharp.Main\Abstract\Account.puml
!include .\\.\Boolean.CSharp.Main\Abstract\MessageProvider.puml
!include .\\.\Boolean.CSharp.Main\Abstract\Request.puml
!include .\\.\Boolean.CSharp.Main\Class\ConsoleMessage.puml
!include .\\.\Boolean.CSharp.Main\Class\CurrentAccount.puml
!include .\\.\Boolean.CSharp.Main\Class\OverdraftRequest.puml
!include .\\.\Boolean.CSharp.Main\Class\SavingAccount.puml
!include .\\.\Boolean.CSharp.Main\Class\Transaction.puml
!include .\\.\Boolean.CSharp.Main\Enums\Enums.puml
!include .\\.\Boolean.CSharp.Main\Interface\IBalanceRequest.puml
!include .\\.\Boolean.CSharp.Main\Interface\IMessage.puml
!include .\\.\Boolean.CSharp.Main\Interface\IOverdraftable.puml
!include .\\.\Boolean.CSharp.Main\obj\Debug\net9.0\.NETCoreApp,Version=v9.0.AssemblyAttributes.puml
!include .\\.\Boolean.CSharp.Main\obj\Debug\net9.0\Boolean.CSharp.Main.AssemblyInfo.puml
!include .\\.\Boolean.CSharp.Main\obj\Debug\net9.0\Boolean.CSharp.Main.GlobalUsings.g.puml
@enduml
